name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Deploy in cf
        uses: rk-1988/logging@main
        with: 
          API:      ${{ secrets.CF_API }}
          ORG:      ${{ secrets.CF_ORG }}
          SPACE:    ${{ secrets.CF_SPACE }}
          USERNAME: ${{ secrets.CF_USERNAME }}
          PASSWORD: ${{ secrets.CF_PASSWORD }}
#          manifest: manifest.yml
          command: target
          validate: false
